#!/bin/bash
#
#SBATCH --job-name=vasp
#SBATCH --output=job_%j.out
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=36
#SBATCH --time=1:00:00
#SBATCH --partition=regular

module load mpi/intelmpi/2017.4.239

# VASP Location
EXE=/public/software/vasp/vasp.5.4.1-impi/bin/vasp_std

# run the job
for i in  5.1 5.2 5.3 5.4 5.5 5.6 5.7 ; do
cat >POSCAR <<!
cubic diamond
   $i
  0.0    0.5    0.5
  0.5    0.0    0.5
  0.5    0.5    0.0
  Si
  2
Direct
  0.00  0.00  0.00
  0.25  0.25  0.25
!
echo "a = $i"
srun --mpi=pmi2 $EXE
E=`cat OSZICAR | awk '/F=/ {print $3}'`
echo $i $E  >>summary.txt
done
